### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [1]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([25, 13, 82, 36, 22, 10, 76, 89, 56, 81, 17, 78, 99, 89, 41],
      dtype=int32)

In [2]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[32, 95, 15,  6],
       [23, 83, 67,  9],
       [59, 54, 49, 44],
       [14, 91, 40, 15],
       [14, 32, 47, 12],
       [24, 58,  8, 98]], dtype=int32)

In [8]:
np.sort(a)    # ascending
np.sort(a)[::-1]    # descending

array([99, 89, 89, 82, 81, 78, 76, 56, 41, 36, 25, 22, 17, 13, 10],
      dtype=int32)

In [ ]:
np.sort(b,axis=0)   # axis=0 for column and axis=1 for row

array([[14, 32,  8,  6],
       [14, 54, 15,  9],
       [23, 58, 40, 12],
       [24, 83, 47, 15],
       [32, 91, 49, 44],
       [59, 95, 67, 98]], dtype=int32)

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [9]:
np.append(a,200)

array([ 25,  13,  82,  36,  22,  10,  76,  89,  56,  81,  17,  78,  99,
        89,  41, 200])

In [13]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[32.        , 95.        , 15.        ,  6.        ,  0.1674835 ],
       [23.        , 83.        , 67.        ,  9.        ,  0.77260144],
       [59.        , 54.        , 49.        , 44.        ,  0.55361032],
       [14.        , 91.        , 40.        , 15.        ,  0.87751951],
       [14.        , 32.        , 47.        , 12.        ,  0.50594191],
       [24.        , 58.        ,  8.        , 98.        ,  0.85006693]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [15]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [16]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [17]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [18]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [19]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [20]:
# code
a.shape

(15,)

In [21]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [22]:
np.expand_dims(a,axis=1)

array([[25],
       [13],
       [82],
       [36],
       [22],
       [10],
       [76],
       [89],
       [56],
       [81],
       [17],
       [78],
       [99],
       [89],
       [41]], dtype=int32)

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [23]:
a

array([25, 13, 82, 36, 22, 10, 76, 89, 56, 81, 17, 78, 99, 89, 41],
      dtype=int32)

In [24]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 2,  6,  7,  8,  9, 11, 12, 13]),)

In [25]:
# replace all values > 50 with 0
np.where(a>50,0,a)


array([25, 13,  0, 36, 22, 10,  0,  0,  0,  0, 17,  0,  0,  0, 41],
      dtype=int32)

In [26]:
np.where(a%2 == 0,0,a)

array([25, 13,  0,  0,  0,  0,  0, 89,  0, 81, 17,  0, 99, 89, 41],
      dtype=int32)

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [27]:
# code
a

array([25, 13, 82, 36, 22, 10, 76, 89, 56, 81, 17, 78, 99, 89, 41],
      dtype=int32)

In [28]:
np.argmax(a)

np.int64(12)

In [29]:
b

array([[32, 95, 15,  6],
       [23, 83, 67,  9],
       [59, 54, 49, 44],
       [14, 91, 40, 15],
       [14, 32, 47, 12],
       [24, 58,  8, 98]], dtype=int32)

In [30]:
np.argmax(b,axis=0)

array([2, 0, 1, 5])

In [31]:
np.argmax(b,axis=1)

array([1, 1, 0, 1, 2, 3])

In [32]:
# np.argmin
np.argmin(a)

np.int64(5)

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [33]:
a

array([25, 13, 82, 36, 22, 10, 76, 89, 56, 81, 17, 78, 99, 89, 41],
      dtype=int32)

In [34]:
np.cumsum(a)

array([ 25,  38, 120, 156, 178, 188, 264, 353, 409, 490, 507, 585, 684,
       773, 814])

In [35]:
b

array([[32, 95, 15,  6],
       [23, 83, 67,  9],
       [59, 54, 49, 44],
       [14, 91, 40, 15],
       [14, 32, 47, 12],
       [24, 58,  8, 98]], dtype=int32)

In [36]:
np.cumsum(b,axis=1)

array([[ 32, 127, 142, 148],
       [ 23, 106, 173, 182],
       [ 59, 113, 162, 206],
       [ 14, 105, 145, 160],
       [ 14,  46,  93, 105],
       [ 24,  82,  90, 188]])

In [37]:
np.cumsum(b)

array([ 32, 127, 142, 148, 171, 254, 321, 330, 389, 443, 492, 536, 550,
       641, 681, 696, 710, 742, 789, 801, 825, 883, 891, 989])

In [38]:
# np.cumprod
np.cumprod(a)

array([                  25,                  325,                26650,
                     959400,             21106800,            211068000,
                16041168000,        1427663952000,       79949181312000,
           6475883686272000,   110090022666624000,  8587021767996672000,
        1564927641031153664, -8295392537903736832, -8069700727281281024])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis. 

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [39]:
a

array([25, 13, 82, 36, 22, 10, 76, 89, 56, 81, 17, 78, 99, 89, 41],
      dtype=int32)

In [40]:
np.percentile(a,50)

np.float64(56.0)

In [41]:
np.median(a)

np.float64(56.0)

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [42]:
a

array([25, 13, 82, 36, 22, 10, 76, 89, 56, 81, 17, 78, 99, 89, 41],
      dtype=int32)

In [43]:
np.histogram(a,bins=[0,50,100])

(array([7, 8]), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [44]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [45]:
a

array([25, 13, 82, 36, 22, 10, 76, 89, 56, 81, 17, 78, 99, 89, 41],
      dtype=int32)

In [ ]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [46]:
a

array([25, 13, 82, 36, 22, 10, 76, 89, 56, 81, 17, 78, 99, 89, 41],
      dtype=int32)

In [47]:
np.flip(a)

array([41, 89, 99, 78, 17, 81, 56, 89, 76, 10, 22, 36, 82, 13, 25],
      dtype=int32)

In [48]:
b

array([[32, 95, 15,  6],
       [23, 83, 67,  9],
       [59, 54, 49, 44],
       [14, 91, 40, 15],
       [14, 32, 47, 12],
       [24, 58,  8, 98]], dtype=int32)

In [49]:
np.flip(b,axis=1)

array([[ 6, 15, 95, 32],
       [ 9, 67, 83, 23],
       [44, 49, 54, 59],
       [15, 40, 91, 14],
       [12, 47, 32, 14],
       [98,  8, 58, 24]], dtype=int32)

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array. 

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [50]:
a

array([25, 13, 82, 36, 22, 10, 76, 89, 56, 81, 17, 78, 99, 89, 41],
      dtype=int32)

In [51]:
np.put(a,[0,1],[110,530])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis. 

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [52]:
a

array([110, 530,  82,  36,  22,  10,  76,  89,  56,  81,  17,  78,  99,
        89,  41], dtype=int32)

In [53]:
np.delete(a,[0,2,4])

array([530,  36,  10,  76,  89,  56,  81,  17,  78,  99,  89,  41],
      dtype=int32)

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [54]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [55]:
np.intersect1d(m,n)

array([3, 4, 5])

In [56]:
np.setdiff1d(n,m)

array([6, 7])

In [57]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [59]:
m[np.in1d(m,1)]

AttributeError: module 'numpy' has no attribute 'in1d'

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [60]:
a

array([110, 530,  82,  36,  22,  10,  76,  89,  56,  81,  17,  78,  99,
        89,  41], dtype=int32)

In [61]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 75, 36, 25, 25, 75, 75, 56, 75, 25, 75, 75, 75, 41],
      dtype=int32)