### Creating Numpy Arrays


In [3]:
# np.array
import numpy as np

a = np.array([1,2,3])
print (a)
print (type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [6]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]])
print (b)

c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print (c)


[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [10]:
# dtype

a = np.array([1,2,3], dtype=float)
print (a)
b = np.array([1,2,3], dtype=bool)
print (b)

[1. 2. 3.]
[ True  True  True]


In [11]:
# np.arange

np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
# with reshape

np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [15]:
# np.ones and np.zeros

a = np.ones((3,4))
print(a)
b = np.zeros((3,4))
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [18]:
# np.random

np.random.random((3,3))

array([[0.96820941, 0.47129293, 0.9637846 ],
       [0.90498054, 0.29317461, 0.3638781 ],
       [0.45620113, 0.55500657, 0.09059344]])

In [20]:
# np.linspace

np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [21]:
# np.identity

np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Array Attributes

In [22]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [26]:
# ndim means number of dimensions

a1.ndim
a2.ndim
a3.ndim


3

In [ ]:
# shape  ( how much items exist in every dimension)

a1.shape
a2.shape
a3.shape

(2, 2, 2)

In [32]:
# size means number od items

a1.size
a2.size
a3.size

8

In [34]:
# itemsize ( every item take how much size i memory)

a1.itemsize
a2.itemsize
a3.itemsize

8

In [37]:
# dtype ( datatype of items)
 
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


### Changing Datatype

In [38]:
# astype

a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operations

In [4]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [53]:
# scalar operations

# arithmetic

a1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [56]:
# relational

print(a2 > 15)
print(a2 < 15)
print(a2 == 15)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]
[[ True  True  True False]
 [False False False False]
 [False False False False]]
[[False False False  True]
 [False False False False]
 [False False False False]]


In [57]:
# vector operations
# arithmetic

print(a1 + a2)

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]


### Array Functions

In [61]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[47., 99., 92.],
       [59., 55., 42.],
       [92., 93., 17.]])

In [68]:
# max/min/sum/prod
# 0 -> col and 1 -> row

print (np.max(a1))
print (np.min(a1))
print (np.sum(a1))
print (np.prod(a1))

99.0
17.0
596.0
8486030115874080.0


In [70]:
# mean/median/std/var

print (np.mean(a1))
print (np.median(a1))
print (np.std(a1))
print (np.var(a1))

66.22222222222223
59.0
27.238770480400735
741.9506172839506


In [6]:
# trigonomoetric functions

print (np.sin(a1))
print (np.cos(a1))

[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]]
[[ 1.          0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029  0.75390225]
 [-0.14550003 -0.91113026 -0.83907153  0.0044257 ]]


In [7]:
# dot product

a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [10]:
# log and exponents

print (np.log(a1))
print (np.exp(a1))

[[      -inf 0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947 1.94591015]
 [2.07944154 2.19722458 2.30258509 2.39789527]]
[[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03]
 [2.98095799e+03 8.10308393e+03 2.20264658e+04 5.98741417e+04]]


C:\Users\hamza\AppData\Local\Temp\ipykernel_18464\3225808568.py:3: RuntimeWarning: divide by zero encountered in log
  print (np.log(a1))


In [13]:
# round/floor/ceil

print (np.round(np.random.random((2,3))*100))
print (np.floor(np.random.random((2,3))*100))
print (np.ceil(np.random.random((2,3))*100))

[[22. 22. 23.]
 [54. 46. 84.]]
[[78.  1. 39.]
 [48. 97. 46.]]
[[67. 99. 92.]
 [40. 92. 57.]]


### Indexing and Slicing

In [14]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
print (a1)
print (a2)
print (a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [18]:
a2[1,2]

np.int64(6)

In [20]:
a3[1,1,1]

np.int64(7)

In [21]:
a2[0,:]

array([0, 1, 2, 3])

In [22]:
a2[:,0]

array([0, 4, 8])

In [24]:
a2[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [25]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [28]:
a3[2,0::2,0::2]

array([[18, 20],
       [24, 26]])

### Iterating

In [29]:
print (a1)
print (a2)
print (a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [31]:
a1

for i in a1:
    print (i)

0
1
2
3
4
5
6
7
8
9


In [32]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [34]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [35]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [37]:
for i in np.nditer(a3):    # nditer convert multi-dimension array into single-dimension
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [43]:
# Reshape

np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
# Transpose

print (np.transpose(a2))
print (a2.T)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [49]:
# Ravel (convert multi-dimension array into one dimension)

a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Stacking

In [61]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
print(a4)
print(a5)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [56]:
# Horizontal Stacking
print (np.hstack((a4,a5)))


[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]


In [54]:
# Vertical Stacking
print (np.vstack((a4,a5)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


### Splitting

In [ ]:
# Horizontal Splitting

print (np.hsplit(a4,2))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [63]:
# Vertical Splittig
a6 = np.arange(1,17).reshape(4,4)
print(a6)
print (np.vsplit(a6,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]]), array([[13, 14, 15, 16]])]
